
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 10 19:32:33 UYT 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int ROOT = 9;
  public static final int SLASH = 16;
  public static final int CONCAT = 12;
  public static final int TRUE = 6;
  public static final int COLON = 3;
  public static final int TILDE = 18;
  public static final int L_BRACKET = 10;
  public static final int DIFFERENCE = 14;
  public static final int STRING = 19;
  public static final int COMMA = 2;
  public static final int INTERSECT = 15;
  public static final int EOF = 0;
  public static final int UNION = 13;
  public static final int FALSE = 7;
  public static final int DOT = 17;
  public static final int error = 1;
  public static final int IDS = 5;
  public static final int R_BRACKET = 11;
  public static final int NULL = 4;
  public static final int DOUBLE = 8;
}

