
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 08 16:22:53 UYT 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int ROOT = 21;
  public static final int TAG = 8;
  public static final int SUBSTRACT = 16;
  public static final int SLASH = 14;
  public static final int CONCAT = 12;
  public static final int TRUE = 10;
  public static final int COLON = 5;
  public static final int TILDE = 18;
  public static final int L_BRACKET = 2;
  public static final int STRING = 7;
  public static final int COMMA = 4;
  public static final int EOF = 0;
  public static final int UNION = 17;
  public static final int FALSE = 11;
  public static final int DOT = 20;
  public static final int error = 1;
  public static final int REGEX = 13;
  public static final int R_BRACKET = 3;
  public static final int SPACES = 19;
  public static final int INTER = 15;
  public static final int NULL = 6;
  public static final int DOUBLE = 9;
}

