
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 10 18:43:31 UYT 2017
//----------------------------------------------------

package lang.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int SLASH = 9;
  public static final int UNION = 6;
  public static final int L_BRACKET = 3;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int CONCAT = 5;
  public static final int TILDE = 11;
  public static final int INTERSECT = 8;
  public static final int IDS = 12;
  public static final int DOT = 10;
  public static final int ROOT = 2;
  public static final int DIFFERENCE = 7;
  public static final int error = 1;
  public static final int R_BRACKET = 4;
}

